version: "3.9"

services:
  api:
    build:
      context: .
      target: dev
    env_file: .env
    ports:
      - "3001:3001"
    volumes:
      - ./surgicai_api:/surgicai_api
    depends_on:
      - db
    networks:
      - surgicai_network

  db:
    image: postgres:16.9
    user: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=surgicai
    ports:
      - '5433:5432'
    volumes: 
      - surgicai_db:/var/lib/postgresql/data
    networks:
      - surgicai_network

volumes:
  surgicai_db:
    driver: local

networks:
  surgicai_network:
