"""initial migration, user model

Revision ID: 1
Revises: 
Create Date: 2025-07-17 15:10:10.507867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

USER_TYPE = sa.Enum(
    "ADMIN",
    "SURGEON",
    "ORG_ADMIN",
    "BILLER",
    name="usertype",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("prefix", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=55), nullable=False),
        sa.Column("last_name", sa.String(length=155), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "user_type",
            USER_TYPE,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    try:
        USER_TYPE.drop(op.get_bind(), checkfirst=True)
    except Exception:
        pass
    # ### end Alembic commands ###
