"""operative description field

Revision ID: 2
Revises: 1
Create Date: 2025-08-07 19:57:25.070192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2"
down_revision: Union[str, None] = "1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "op_notes", sa.Column("operative_description", sa.Text(), nullable=True)
    )
    op.create_unique_constraint(None, "op_notes", ["id"])
    op.create_unique_constraint(None, "organizations", ["id"])
    op.create_unique_constraint(None, "templates", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "templates", type_="unique")
    op.drop_constraint(None, "organizations", type_="unique")
    op.drop_constraint(None, "op_notes", type_="unique")
    op.drop_column("op_notes", "operative_description")
    # ### end Alembic commands ###
