"""user opnote relationship

Revision ID: 3
Revises: 2
Create Date: 2025-07-17 20:37:19.107900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3"
down_revision: Union[str, None] = "2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "op_notes", sa.Column("owner_id", sa.String(length=255), nullable=False)
    )
    op.create_unique_constraint(None, "op_notes", ["id"])
    op.create_foreign_key(None, "op_notes", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "op_notes", type_="foreignkey")
    op.drop_constraint(None, "op_notes", type_="unique")
    op.drop_column("op_notes", "owner_id")
    # ### end Alembic commands ###
