"""apply cascade deletes

Revision ID: 5
Revises: 4
Create Date: 2025-07-21 16:13:00.755990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5"
down_revision: Union[str, None] = "4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("op_notes_owner_id_fkey", "op_notes", type_="foreignkey")
    op.create_foreign_key(
        None, "op_notes", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.create_unique_constraint(None, "templates", ["id"])
    op.drop_constraint("templates_owner_id_fkey", "templates", type_="foreignkey")
    op.create_foreign_key(
        None, "templates", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "templates", type_="foreignkey")
    op.create_foreign_key(
        "templates_owner_id_fkey", "templates", "users", ["owner_id"], ["id"]
    )
    op.drop_constraint(None, "templates", type_="unique")
    op.drop_constraint(None, "op_notes", type_="foreignkey")
    op.create_foreign_key(
        "op_notes_owner_id_fkey", "op_notes", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###
