"""add optimization metadata

Revision ID: 6
Revises: 5
Create Date: 2025-07-28 22:28:56.369172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from surgicai_api.models.fields import JsonEncodedDict


# revision identifiers, used by Alembic.
revision: str = "6"
down_revision: Union[str, None] = "5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "op_notes",
        sa.Column(
            "optimization_metadata",
            JsonEncodedDict(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("op_notes", "optimization_metadata")
    # ### end Alembic commands ###
